const members = [
  {
    Name: "Om Dave",
    Email: "co22btech11006@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1H6HlHHTU1HE1Wkt3WxJI775kfpI-Gysq",
    Designation: "Events",
  },
  {
    Name: "Ayush Jaiswal ",
    Email: "ce22btech11007@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1Uarqo3ShaFD0t2sEl3JSHKfKN3EImEQG",
    Designation: "Events",
  },
  {
    Name: "Yash",
    Email: "me22btech11060@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1iZu_PrXQlOvNpLhA3R8LAKN3bAVT5wsn",
    Designation: "Inbound",
  },
  {
    Name: "Shreya Sridhar",
    Email: "ic22btech11015@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1rbLe22srcmlGh2i7AonWggud9e-7q3gO",
    Designation: "Inbound",
  },
  {
    Name: "Aman Bhasin",
    Email: "es21btech11006@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1981cFESEkVc1jurEtQg4bn6vkZFfxsBm",
    Designation: "Head - Event Domain",
  },
  {
    Name: "Yasir Usmani",
    Email: "ai22btech11031@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1L_VcsRss8excE_pmrcUv4JJ2NEznJmMN",
    Designation: "Inbound",
  },
  {
    Name: "Swapnil Bag",
    Email: "es22btech11034@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1f0PtM-MxHXYHQEIWPJR6sqDfzxJ-zhT8",
    Designation: "Events",
  },
  {
    Name: "Kunwar dushyant singh ",
    Email: "ee22btech11031@iith.ac.in ",
    Photo: "https://drive.google.com/open?id=1if_zqkM2tXyw4ZbVgwa8qhf90v9a8BkS",
    Designation: "Inbound",
  },
  {
    Name: "Rajiv Shailesh Chitale",
    Email: "cs21btech11051@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1YujIFAZE6SMin5PB1LS22j2yeaL6wt4Y",
    Designation: "Senior Core",
  },
  {
    Name: "Ome Bharath J",
    Email: "Ep22btech11019@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1NYPNLlkdvArA0qlXw244c1UXsLaxwqga",
    Designation: "Inbound",
  },
  {
    Name: "Varun Srivastava",
    Email: "ch22btech11038@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1rPpBXRA6iZDn21MmV11Ia46nYpxJNoNJ",
    Designation: "Events",
  },
  {
    Name: "Mehwish Naz",
    Email: "ch22btech11021@gmail.com",
    Photo: "https://drive.google.com/open?id=1xDkAyJ0yogtQsS7knevsbRRHS_WIcirB",
    Designation: "Events",
  },
  {
    Name: "Paban shinde ",
    Email: "co22btech11008@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1KWKYghj3KAFyUp22xkSgxP7AyvUpOjWW",
    Designation: "Inbound",
  },
  {
    Name: "Vyaas",
    Email: "ep22btech11031@iith.ac.in",
    Photo: "https://drive.google.com/open?id=15PYGxcd6ECwAiY3OtzTNUCngwAJaMAgs",
    Designation: "Media & PR",
  },
  {
    Name: "Shriram H",
    Email: "me22btech11023@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1wnCSmV9VHWffV7mQS-qURhFj4tJLdgwT",
    Designation: "Media & PR",
  },
  {
    Name: "Ambica Govind ",
    Email: "ep21btech11007@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1wASO2QjGjqnRD_VrrrwUYfIk_coI4QE9",
    Designation: "Mentor",
  },
  {
    Name: "Rushikesh Nilapalle ",
    Email: "es20btech11022@iith.ac.in",
    Photo: "https://drive.google.com/open?id=12Sv9ycLugn7y6e-gGwbuJfLu07aZQ2Fz",
    Designation: "Mentor",
  },
  {
    Name: "Ansh Vardhan",
    Email: "es21btech11008@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1fpIvvGrtoyHrpqRbUm81WbkpwcgBlabn",
    Designation: "Senior Core",
  },
  {
    Name: "Vaishnavi Vyasraj",
    Email: "ep22btech11029@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1-NCEB6WCLnSC9W4Ody7GE2L6Z-BJV7xU",
    Designation: "Events",
  },
  {
    Name: "Ashish Bhardwaj",
    Email: "ms22btech11007@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1b14O42xgOkmT2vOeNVkTJbe16xZKfAvl",
    Designation: "Events",
  },
  {
    Name: "Harman Singh ",
    Email: "me22btech11024@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1LUEm9SH0NoszN_TzMC1YSxiG0RLO5TyJ",
    Designation: "Inbound",
  },
  {
    Name: "Sameer kendal",
    Email: "ee22btech11044@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1KDPt2QHNPgRZ6fu_dt8AoCvNGJCYHCRP",
    Designation: "Inbound",
  },
  {
    Name: "Thameem Rasheed ",
    Email: "bd22bdes11018@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1urfAFl-1-Ezxun7xJp8889-Vz_eUsKAV",
    Designation: "Inbound",
  },
  {
    Name: "Kartik Agrawal",
    Email: "ee21btech11030@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1ywwk87rNvsEA1YhEfi_G9Tsip_6lOViA",
    Designation: "Senior Core",
  },
  {
    Name: "Pragya Yadav",
    Email: "ch21btech11023@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1QAfwfzTdW2y9dIonF674i5ZUMD8ZRShR",
    Designation: "Inbound Head",
  },
  {
    Name: "A.Padmaprabhan",
    Email: "me22btech11001@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1UsNxhbAa5kmiuqFJ1ftD8_d2HGRp7rcM",
    Designation: "Media & PR",
  },
  {
    Name: "Abhijit Kasle ",
    Email: "ep21btech11002@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1FtHQBFmKiHzAQMQzpZ5ac4VJo5IHs0ut",
    Designation: "Media Head",
  },
  {
    Name: "Piyush Kothawade",
    Email: "es22btech11026@iith.ac.in",
    Photo: "https://drive.google.com/open?id=17z1arL4pYNcdOzt_9tZuR3TOgRL-R1QF",
    Designation: "Events",
  },
  {
    Name: "Devansh Jain",
    Email: "ee22btech11018@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1BMESp5aYVsTK9asunDWEk9hiAwMuUbxF",
    Designation: "Events",
  },
  {
    Name: "Kunj Panchal",
    Email: "ep21btech11017@iith.ac.in",
    Photo: "https://drive.google.com/open?id=1b9gcBqQ7E7LezYrBKfTjFI1Ru8xLuawN",
    Designation: "Overall Head",
  },
];
